/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.0.9 scene.gltf
Author: 3Dee (https://sketchfab.com/mellydeeis)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/subatomic-particle-fx-74df90d8e73841fabac0aab1c855280b
Title: Subatomic Particle FX
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes['Material-material'].geometry} material={materials.Material} position={[0.04, 0.79, 0.12]} rotation={[0, -Math.PI / 2, 0]} />
        <mesh geometry={nodes['Material_002-material'].geometry} material={materials['Material.002']} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
